### PR TITLE
Add GeoJSON compliant fromJson and toJson

### PR DESCRIPTION
**Pull request by JonIsAmazingYa**
Proposal for adding fromJson and toJson serialization for LatLng object

### CODE REVIEW

**Comment by JonIsAmazingYa** [comment]
@jifalops would it be possible to take a look at this?

**Comment by jifalops** [comment]
I'm a little apprehensive about hardcoding the `coordinates` key. Other JsonSerializable() uses only specify the value.

**Comment by JonIsAmazingYa** [comment]
Could you provide an example of a `toJson` method which provides a value only?

**Comment by jifalops** [comment]
```dart 
@JsonSerializable
GeoData {
  final Set<LatLng> coords;
}
```
The containing class decides the key here. It doesn't really matter though, I'm just going to accept this.

**Comment by jifalops** [comment]
released in 0.8.1

**Pull request merged**
